/**
 * This package contains the Spring-web MVC @Controllers that respond to browser HTTP requests from
 * HTML generated by the Thymeleaf template engine.
 */
package com.aestheticsw.jobkeywords.web.html;